#!/run/current-system/sw/bin/bash


parted /dev/$1 -- mklabel msdos &&
parted /dev/$1 -- mkpart primary 1MB 100% &&
parted /dev/$1 -- set 1 boot on &&
mkfs.ext4 -L NIXROOT /dev/${1}1 &&
mount /dev/disk/by-label/NIXROOT /mnt &&
nixos-install --flake .#nixos &&

mkdir /mnt/home/rizqirazkafi/nixos-testing-config
git clone https://github.com/rizqirazkafi/nixos-testing-config /mnt/home/rizqirazkafi/nixos-testing-config


